# -*- coding: utf-8 -*-
"""Diffusion-based-Text- to -Video Generative Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZeNGLPTGGw0EkGww8DOq3uHbE7UdLQMB
"""

! pip install diffusers transformers accelerate

import torch
from diffusers import DiffusionPipeline, DPMSolverMultistepScheduler
from diffusers.utils import export_to_video

pipe = DiffusionPipeline.from_pretrained("ali-vilab/text-to-video-ms-1.7b", torch_dtype = torch.float16, variant="fp16")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()

prompt = "batman is riding horse"
video_frames = pipe(prompt,num_inference_steps=25).frames
video_path = export_to_video(video_frames)
video_name = video_path.replace('/temp','')
print('Name:',video_name)
torch.cuda.empty_cache()